// db name
const DB_NAME = "chatverse";

// events
const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

export { DB_NAME, ALERT, REFETCH_CHATS, NEW_ATTACHMENT, NEW_MESSAGE_ALERT };
